In [2]:
import os
import sys
import glob
import time
import pandas as pd
import json
import datetime

# Data Paths

In [3]:
data_path = "/DATA/7A/xblock/"
df_path = "/home/aakyildiz/tokens/dataframes/"

#
erc20_transactions_path = "ERC20Transactions/uncompressed"
erc721_transactions_path = "ERC721Transactions/uncompressed"
internal_transactions_path = "InternalTransactions/uncompressed"
normal_transactions_path = "NormalTransactions/uncompressed"

#token information
token_info_path = "TokenInfo/uncompressed/"
erc20_filename = "ERC20TokenInfo.csv"
erc721_filename = "ERC721TokenInfo.csv"

#dataframes
internalTransactions_filename = "internalTransactions.df"
erc20Transactions_filename = "erc20Transactions.df"
erc721Transactions_filename = "erc721Transactions.df"

# Get Token Information and Transactions

##  get erc721 token information

In [4]:
#get erc721 token information
erc721InfoDF = pd.read_csv(data_path + token_info_path + erc721_filename, error_bad_lines=False)
erc721InfoDF = erc721InfoDF[erc721InfoDF['decimal'] != "None"].astype({"decimal": float})
print(erc721InfoDF.shape[0])
erc721InfoDF.head()

7691

,address,name,symbol,decimal
0,0x27b4bc90fbe56f02ef50f2e2f79d7813aa8941a7,gego.dego,GEGO,54084.0
1,0x3f9d7b15763f57d7f5015901eaccca27ce996bb2,Polysphere,PLYSPR,5.0
2,0x06012c8cf97bead5deae237070f9587f8e7a266d,CryptoKitties,CK,1996597.0
3,0xbbe7aeb729e65e3854a30d583cee6a28434eb841,Polysphere,POLY,0.0
4,0x2fb5d7dda4f1f20f974a0fdd547c38674e8d940c,KnightStory Item,MyKI,13250.0

##  get erc20 token information

In [15]:
#get erc20 token information
#line 154118 in this file is problematic for some reason
erc20InfoDF = pd.read_csv(data_path + token_info_path + erc20_filename, error_bad_lines=False)
print(erc20InfoDF.shape[0])
erc20InfoDF.head()

226250

b'Skipping line 154118: expected 5 fields, saw 7\n'

,address,name,symbol,totalSupply,decimal
0,0x6b0359f95796327475ad4f12ae4e1047c3a67fa3,FinFine Token,FFT,214285500000,3
1,0x12d79c345cac7b050a5ff0797b5a607e254c73f5,Buytex,BUX,9999999999999,4
2,0x6bc1f3a1ae56231dbb64d3e82e070857eae86045,xensor,XSR,4800000000000000000000000000,18
3,0x10086399dd8c1e3de736724af52587a2044c9fa2,The Midas Touch Gold,TMTG,9161139666073037500000000000,18
4,0xdac17f958d2ee523a2206206994597c13d831ec7,Tether USD,USDT,20817977739617189,6

## read all internal transactions

In [ ]:
#all_files = glob.glob(data_path + internal_transactions_path + "/*.csv")
#
#li = []
#
#for filename in all_files:
#    start = time.time()
#    print("Reading file", filename, "...", end='', flush=True)
#    df = pd.read_csv(filename, index_col=None, header=0)
#    li.append(df)
#    end = time.time()
#    print(" took", end - start, "seconds.")
#    #break #read just the first file
#internalTransactionsDF = pd.concat(li, axis=0, ignore_index=True)

s = time.time()
internalTransactionsDF = pd.read_feather(df_path + internalTransactions_filename)
e = time.time()
print("Took", e - s, " seconds.")
print(internalTransactionsDF.shape[0])
internalTransactionsDF.head(10)

Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/4000000to4999999_InternalTransaction.csv ... took 94.51653051376343 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/6000000to6999999_InternalTransaction.csv ... took 191.7375135421753 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/5000000to5999999_InternalTransaction.csv ... took 178.68031859397888 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/2000000to2999999_InternalTransaction.csv ...

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

 took 524.4415943622589 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/11000000to11999999_InternalTransaction.csv ... took 816.1531925201416 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/7000000to7999999_InternalTransaction.csv ... took 223.20917558670044 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/9000000to9999999_InternalTransaction.csv ... took 341.0996310710907 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/0to999999_InternalTransaction.csv ... took 1.387322187423706 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/10000000to10999999_InternalTransaction.csv ...

## read all erc20 transactions

In [ ]:
#all_files = glob.glob(data_path + erc20_transactions_path + "/*.csv")
#
#li = []
#
#for filename in all_files:
#    start = time.time()
#    print("Reading file", filename, "...", end='', flush=True)
#    df = pd.read_csv(filename, index_col=None, header=0)
#    li.append(df)
#    end = time.time()
#    print(" took", end - start, "seconds.")
#    #break #read just the first file
#erc20TransactionsDF = pd.concat(li, axis=0, ignore_index=True)

s = time.time()
erc20TransactionsDF = pd.read_feather(df_path + erc20Transactions_filename)
e = time.time()
print("Took", e - s, " seconds.")
print(erc20TransactionsDF.shape[0])
erc20TransactionsDF.head()

## read all erc721 transactions

In [10]:
#all_files = glob.glob(data_path + erc721_transactions_path + "/*.csv")
#
#li = []
#
#for filename in all_files:
#    start = time.time()
#    print("Reading file", filename, "...", end="", flush=True)
#    df = pd.read_csv(filename, index_col=None, header=0)
#    li.append(df)
#    end = time.time()
#    print(" took", end - start, "seconds.")
#    #break #read just the first file
#erc721TransactionsDF = pd.concat(li, axis=0, ignore_index=True)

s = time.time()
erc721TransactionsDF = pd.read_feather(df_path + erc721Transactions_filename)
e = time.time()
print("Took", e - s, " seconds.")
print(erc721TransactionsDF.shape[0])
erc721TransactionsDF.head()

Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/3000000to3999999_ERC721Transaction.csv ... took 0.0046367645263671875 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/5000000to5999999_ERC721Transaction.csv ... took 2.7295780181884766 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/9000000to9999999_ERC721Transaction.csv ...

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

 took 7.378101348876953 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/7000000to7999999_ERC721Transaction.csv ... took 4.441650629043579 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/0to999999_ERC721Transaction.csv ... took 0.003723621368408203 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/6000000to6999999_ERC721Transaction.csv ... took 3.5326170921325684 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/11000000to11999999_ERC721Transaction.csv ... took 2.6764400005340576 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/4000000to4999999_ERC721Transaction.csv ... took 2.909425973892212 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/10000000to10999999_ERC721Transaction.csv ... took 2.085366725921631 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/2000000to2999999_ERC721Transaction.csv ... took 0.003330230712890625 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/8000000to8999999_ERC721Transaction.csv ... took 24.33165717124939 seconds.
Reading file /DATA/7A/xblock/ERC721Transactions/uncompressed/1000000to1999999_ERC721Transaction.csv ... took 0.0052602291107177734 seconds.
29634892

,blockNumber,timestamp,transactionHash,tokenAddress,from,to,fromIsContract,toIsContract,tokenId
0,3006260,1484564580,0x9d5fe398fe902975f8508e197ec6c0d0082f8a142a7f...,0xe9436e4cb00f38215a941c7141ee98348fdcce6d,0x002add5778a3d327278a357a4983a57c1894af12,0xa84ab927943d87e2f14afac62af7283e26cf010e,0,0,1000000000000000
1,3053922,1485244952,0xd97c4ddc0f5c0af8c18a093b184de0a8a14e35c87c3f...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x121b1badeda482fa25f01c63ad17bbc2701f9165,0x5d2c24efac49825f682b5d334428f1a5c96acc09,0,1,3441148
2,3053922,1485244952,0xd97c4ddc0f5c0af8c18a093b184de0a8a14e35c87c3f...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x121b1badeda482fa25f01c63ad17bbc2701f9165,0x3effc3bb636a66d39ae016399d787d99e1c286a4,0,0,100000000
3,3053922,1485244952,0xd97c4ddc0f5c0af8c18a093b184de0a8a14e35c87c3f...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x121b1badeda482fa25f01c63ad17bbc2701f9165,0x5d2c24efac49825f682b5d334428f1a5c96acc09,0,1,130000
4,3132454,1486369652,0x2a7ed459141cc841ab5b376ea64dbc7041b333384d7a...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x01d80e458ae6cd5d2bce90b06ff2d3fa993b65f5,0x5d2c24efac49825f682b5d334428f1a5c96acc09,0,1,140576

***

***

***

# Graphs

## Token Transactions Graph

In [12]:
#create a token graph
targetDF = erc721TransactionsDF
targetInfoDF = erc721InfoDF

#target = "0x06012c8cf97bead5deae237070f9587f8e7a266d" # Crypto Kitties
#target = "0x629cdec6acc980ebeebea9e5003bcd44db9fc5ce" # Gods Unchained Cards
target = "0x60f80121c31a0d46b5279700f9df786054aa5ee5" #Rarible
#target = "0xbd13e53255ef917da7557db1b7d2d5c38a2efe24" #DozzerDoll

name = targetInfoDf[targetInfoDF["address"] == target].values[0][1].replace(" ", "")

tknTransactionsDF = targetDF[targetDF["tokenAddress"] == target][["from", "to", "timestamp"]]

nodes = pd.unique(tknTransactionsDF[["from", "to"]].values.ravel())
edges = tknTransactionsDF.values

graph = {}
graph["nodes"] = nodes.tolist()
graph["edges"] = edges.tolist()
graph["#nodes"] = len(nodes)
graph["#edges"] = len(edges)
graph["name"] = name
graph["edge"] = "from to timestamp"
graph["node"] = "addresses"
graph["comments"] = ""

#g_file_name = name + ".edgelist"
m_file_name = name + ".json"
os.mkdir(name)
with open(name + "/" + m_file_name, 'w') as f:
    json.dump(graph, f, indent=4)
#tknTransactionsDF.to_csv(os.getcwd() + "/" + tokenName + "/" + g_file_name, sep ='\t', index=False, header=False)

tknTransactionsDF

,from,to,timestamp
9741195,0xa8e4416fecae4620bac2cab913d3343daef07e06,0x5ea1d56d0dde1ca5b50c277275855f69edefa169,1601958250
9741238,0x0000000000000000000000000000000000000000,0x87b90d8635e0e725f0db0ce9926be37f915f930d,1601958437
9741309,0x0000000000000000000000000000000000000000,0xb955f54bc46d7682a232b4f1a3f174e7c7d0fe5a,1601958724
9741319,0x85f24ec48009865b7fe2b699d1e4d4485efe99d5,0x5be10f3434bc1ac6c0a34f86da39ea0095392f21,1601958948
9741342,0x0000000000000000000000000000000000000000,0x95efb7ce9d9cade588d3a9856e5918206b50450d,1601959086
...,...,...,...
13696359,0x9d0c9a4efb7d88e020eb7eebe406c138be157501,0x0000000000000000000000000000000000000000,1601956564
13696393,0xe009187edaa31043315c37b6aad59086c4551c27,0x0000000000000000000000000000000000000000,1601956836
13696544,0x7ffd68ae92ddc5c7d9a3e29e37166823ad0d46db,0x4ecd82114f73c9f2debab6f08c9891fc742ad472,1601957566
13696617,0x9d0c9a4efb7d88e020eb7eebe406c138be157501,0x0000000000000000000000000000000000000000,1601957769
13696621,0x0000000000000000000000000000000000000000,0xe0afc0758ebc13c7f45f5f5d9991d49a2f58970c,1601957803

## Contract Transactions Graph

In [26]:
name = "EthContractTransactions"
targetDF = internalTransactionsDF

contractTransactionsDF = targetDF[(targetDF["fromIsContract"] == 1) & 
                                  (targetDF["toIsContract"] == 1)
                                 ][["from", "to", "timestamp"]]

nodes = pd.unique(contractTransactionsDF[["from", "to"]].values.ravel())
edges = contractTransactionsDF.values

for e in edges:
        t = int(e[2])
        e[2] = t
        ts = int("1284101485")

    # if you encounter a "year is out of range" error the timestamp
    # may be in milliseconds, try `ts /= 1000` in that case
    #print(datetime.utcfromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'))
                
graph = {}
graph["nodes"] = nodes.tolist()
graph["edges"] = edges.tolist()
graph["#nodes"] = len(nodes)
graph["#edges"] = len(edges)
graph["name"] = "Eth Contract Transactions"
graph["edge"] = "from to timestamp"
graph["node"] = "addresses"
graph["comments"] = ""

print(len(nodes), len(edges))
#g_file_name = name + ".edgelist"
m_file_name = name + ".json"
os.mkdir(name)
with open(name + "/" + m_file_name, 'w') as f:
    json.dump(graph, f, indent=4)
#contractTransactionsDF.to_csv(os.getcwd() + "/" + name + "/" + g_file_name, sep ='\t', index=False, header=False)

print(contractTransactionsDF.shape[0])
contractTransactionsDF

3309220 52844135
52844135

,from,to,timestamp
0,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xedce883162179d4ed5eb9bb2e7dccf494d75b3a0,1499633567
1,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0x88de41a34871e239c52926f920efb4eefa0f3de3,1499633567
2,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xedce883162179d4ed5eb9bb2e7dccf494d75b3a0,1499633567
3,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xedce883162179d4ed5eb9bb2e7dccf494d75b3a0,1499633567
4,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xaaaf91d9b90df800df4f55c205fd6989c977e73a,1499633567
...,...,...,...
61158657,0x06012c8cf97bead5deae237070f9587f8e7a266d,0xecde0842e309c4b2d15c074512404207335f3096,1517319688
61158659,0x39243a59d34169eeb0cac2752a21b982408a0194,0x06012c8cf97bead5deae237070f9587f8e7a266d,1517319688
61158661,0x9b993ffb5df123822dc6cdecaedb6f2a61675a6e,0x5b28878c6a779b759a98544a36d25ea43724cd06,1517319688
61158662,0x9b993ffb5df123822dc6cdecaedb6f2a61675a6e,0xfae4ee59cdd86e3be9e8b90b53aa866327d7c090,1517319688
61158663,0x9b993ffb5df123822dc6cdecaedb6f2a61675a6e,0xfae4ee59cdd86e3be9e8b90b53aa866327d7c090,1517319688

## Print Edge List

In [16]:
edges = graph["edges"]
out = name + "/" + name + ".edgelist"

labels = {}
c = 0

start = time.time()
print("Creating graph", out, "...", end='', flush=True)
#get smallest time stamp
mint = sys.maxsize
for e in edges:
        t = int(e[2])
        if t < mint:
                mint = t
with open(out, "w") as o:
        for e in edges:
                u = e[0]
                v = e[1]
                t = e[2]
                if u not in labels:
                        labels[u] = c
                        c += 1
                u = labels[u]
                if v not in labels:
                        labels[v] = c
                        c += 1
                v = labels[v]
                o.write(str(u) + " " + str(v) + " " + str(int(t) - mint) + "\n")
end = time.time()
print("took", end - start, "seconds.")

Creating graph Rarible/Rarible.edgelist ...took 0.13352131843566895 seconds.