In [1]:
import os
import sys
import glob
import time
import pandas as pd
import json
import datetime

# Data Paths

In [2]:
data_path = "/DATA/7A/xblock/"
df_path = "/DATA/7A/assets/dataframes/"
graph_path = "/DATA/7A/assets/"

#
erc20_transactions_path = "ERC20Transactions/uncompressed"
erc721_transactions_path = "ERC721Transactions/uncompressed"
internal_transactions_path = "InternalTransactions/uncompressed"
normal_transactions_path = "NormalTransactions/uncompressed"

#token information
token_info_path = "TokenInfo/uncompressed/"
erc20_filename = "ERC20TokenInfo.csv"
erc721_filename = "ERC721TokenInfo.csv"

#dataframes
internalTransactions_filename = "internalTransactions.df"
erc20Transactions_filename = "erc20Transactions.df"
erc721Transactions_filename = "erc721Transactions.df"

# Get Token Information and Transactions

##  get erc721 token information

In [3]:
#get erc721 token information
erc721InfoDF = pd.read_csv(data_path + token_info_path + erc721_filename, error_bad_lines=False)
erc721InfoDF = erc721InfoDF[erc721InfoDF['decimal'] != "None"].astype({"decimal": float})
print(erc721InfoDF.shape[0])
erc721InfoDF.head()

7691

,address,name,symbol,decimal
0,0x27b4bc90fbe56f02ef50f2e2f79d7813aa8941a7,gego.dego,GEGO,54084.0
1,0x3f9d7b15763f57d7f5015901eaccca27ce996bb2,Polysphere,PLYSPR,5.0
2,0x06012c8cf97bead5deae237070f9587f8e7a266d,CryptoKitties,CK,1996597.0
3,0xbbe7aeb729e65e3854a30d583cee6a28434eb841,Polysphere,POLY,0.0
4,0x2fb5d7dda4f1f20f974a0fdd547c38674e8d940c,KnightStory Item,MyKI,13250.0

##  get erc20 token information

In [4]:
#get erc20 token information
#line 154118 in this file is problematic for some reason
erc20InfoDF = pd.read_csv(data_path + token_info_path + erc20_filename, error_bad_lines=False)
print(erc20InfoDF.shape[0])
print(erc20InfoDF[erc20InfoDF["address"] == "0x09cabec1ead1c0ba254b09efb3ee13841712be14"])
erc20InfoDF.head()

226250
                                          address  name symbol  \
11025  0x09cabec1ead1c0ba254b09efb3ee13841712be14  None   None

                totalSupply decimal
11025  35395946383708946794      18

b'Skipping line 154118: expected 5 fields, saw 7\n'

,address,name,symbol,totalSupply,decimal
0,0x6b0359f95796327475ad4f12ae4e1047c3a67fa3,FinFine Token,FFT,214285500000,3
1,0x12d79c345cac7b050a5ff0797b5a607e254c73f5,Buytex,BUX,9999999999999,4
2,0x6bc1f3a1ae56231dbb64d3e82e070857eae86045,xensor,XSR,4800000000000000000000000000,18
3,0x10086399dd8c1e3de736724af52587a2044c9fa2,The Midas Touch Gold,TMTG,9161139666073037500000000000,18
4,0xdac17f958d2ee523a2206206994597c13d831ec7,Tether USD,USDT,20817977739617189,6

## read all internal transactions

In [ ]:
#all_files = glob.glob(data_path + internal_transactions_path + "/*.csv")
#
#li = []
#
#for filename in all_files:
#    start = time.time()
#    print("Reading file", filename, "...", end='', flush=True)
#    df = pd.read_csv(filename, index_col=None, header=0)
#    li.append(df)
#    end = time.time()
#    print(" took", end - start, "seconds.")
#    #break #read just the first file
#internalTransactionsDF = pd.concat(li, axis=0, ignore_index=True)

s = time.time()
internalTransactionsDF = pd.read_feather(df_path + internalTransactions_filename)
e = time.time()
print("Took", e - s, " seconds.")
print(internalTransactionsDF.shape[0])
internalTransactionsDF.head(10)

Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/4000000to4999999_InternalTransaction.csv ... took 94.51653051376343 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/6000000to6999999_InternalTransaction.csv ... took 191.7375135421753 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/5000000to5999999_InternalTransaction.csv ... took 178.68031859397888 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/2000000to2999999_InternalTransaction.csv ...

/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

 took 524.4415943622589 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/11000000to11999999_InternalTransaction.csv ... took 816.1531925201416 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/7000000to7999999_InternalTransaction.csv ... took 223.20917558670044 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/9000000to9999999_InternalTransaction.csv ... took 341.0996310710907 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/0to999999_InternalTransaction.csv ... took 1.387322187423706 seconds.
Reading file /DATA/7A/xblock/InternalTransactions/uncompressed/10000000to10999999_InternalTransaction.csv ...

## read all erc20 transactions

In [7]:
#all_files = glob.glob(data_path + erc20_transactions_path + "/*.csv")
#
#li = []
#
#for filename in all_files:
#    start = time.time()
#    print("Reading file", filename, "...", end='', flush=True)
#    df = pd.read_csv(filename, index_col=None, header=0)
#    li.append(df)
#    end = time.time()
#    print(" took", end - start, "seconds.")
#    #break #read just the first file
#erc20TransactionsDF = pd.concat(li, axis=0, ignore_index=True)

s = time.time()
erc20TransactionsDF = pd.read_feather(df_path + erc20Transactions_filename)
e = time.time()
print("Took", e - s, " seconds.")
print(erc20TransactionsDF.shape[0])
erc20TransactionsDF.head()

Took 617.1892807483673  seconds.
601955094

,blockNumber,timestamp,transactionHash,tokenAddress,from,to,fromIsContract,toIsContract
0,462680,1446203330,0x806172da2073b5c3d961a8c613b7e469766ad19c6220...,0xe6ee69495b571e1042f760d7f34009164aff87a2,0xb1a2b43a7433dd150bb82227ed519cd6b142d382,0x9b22a80d5c7b3374a05b446081f97d0a34079e7f,0,0
1,462683,1446203369,0xd5c17b09dcf6e5daa0566d7d2a8245f10a755ecfbf34...,0xe6ee69495b571e1042f760d7f34009164aff87a2,0xb1a2b43a7433dd150bb82227ed519cd6b142d382,0x9b22a80d5c7b3374a05b446081f97d0a34079e7f,0,0
2,462696,1446203551,0x530e047cccef3ea1f78bcdb629661fabe193ba87cd82...,0xe6ee69495b571e1042f760d7f34009164aff87a2,0xb1a2b43a7433dd150bb82227ed519cd6b142d382,0x9b22a80d5c7b3374a05b446081f97d0a34079e7f,0,0
3,477958,1446458222,0x0d58cd643c38a8951ee26a49399d4d5682fab74e96a9...,0xe6ee69495b571e1042f760d7f34009164aff87a2,0xb1a2b43a7433dd150bb82227ed519cd6b142d382,0xcf8470d3388a198418e02aaf8e37392cfbc18867,0,1
4,483333,1446552343,0xd628780ba231cefe6a4f6c3da3b683b16f6151dc9753...,0xf4eced2f682ce333f96f2d8966c613ded8fc95dd,0x9b22a80d5c7b3374a05b446081f97d0a34079e7f,0xd1220a0cf47c7b9be7a2e6ba89f429762e7b9adb,0,0

## read all erc721 transactions

In [4]:
#all_files = glob.glob(data_path + erc721_transactions_path + "/*.csv")
#
#li = []
#
#for filename in all_files:
#    start = time.time()
#    print("Reading file", filename, "...", end="", flush=True)
#    df = pd.read_csv(filename, index_col=None, header=0)
#    li.append(df)
#    end = time.time()
#    print(" took", end - start, "seconds.")
#    #break #read just the first file
#erc721TransactionsDF = pd.concat(li, axis=0, ignore_index=True)

s = time.time()
erc721TransactionsDF = pd.read_feather(df_path + erc721Transactions_filename)
e = time.time()
print("Took", e - s, " seconds.")
print(erc721TransactionsDF.shape[0])
erc721TransactionsDF.head()

Took 10.532785654067993  seconds.
29634892

,blockNumber,timestamp,transactionHash,tokenAddress,from,to,fromIsContract,toIsContract
0,3006260,1484564580,0x9d5fe398fe902975f8508e197ec6c0d0082f8a142a7f...,0xe9436e4cb00f38215a941c7141ee98348fdcce6d,0x002add5778a3d327278a357a4983a57c1894af12,0xa84ab927943d87e2f14afac62af7283e26cf010e,0,0
1,3053922,1485244952,0xd97c4ddc0f5c0af8c18a093b184de0a8a14e35c87c3f...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x121b1badeda482fa25f01c63ad17bbc2701f9165,0x5d2c24efac49825f682b5d334428f1a5c96acc09,0,1
2,3053922,1485244952,0xd97c4ddc0f5c0af8c18a093b184de0a8a14e35c87c3f...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x121b1badeda482fa25f01c63ad17bbc2701f9165,0x3effc3bb636a66d39ae016399d787d99e1c286a4,0,0
3,3053922,1485244952,0xd97c4ddc0f5c0af8c18a093b184de0a8a14e35c87c3f...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x121b1badeda482fa25f01c63ad17bbc2701f9165,0x5d2c24efac49825f682b5d334428f1a5c96acc09,0,1
4,3132454,1486369652,0x2a7ed459141cc841ab5b376ea64dbc7041b333384d7a...,0x55b9a11c2e8351b4ffc7b11561148bfac9977855,0x01d80e458ae6cd5d2bce90b06ff2d3fa993b65f5,0x5d2c24efac49825f682b5d334428f1a5c96acc09,0,1

***

***

***

# Graphs

## Token Transactions Graph

In [14]:
#create a token graph
targetDF = erc20TransactionsDF
targetInfoDF = erc20InfoDF

# games
# 0x06012c8cf97bead5deae237070f9587f8e7a266d Crypto Kitties (erc721)
# 0x629cdec6acc980ebeebea9e5003bcd44db9fc5ce Gods Unchained Cards (erc721)
# 0xbd13e53255ef917da7557db1b7d2d5c38a2efe24 DozzerDoll (erc721)

# marketplaces
# 0x60f80121c31a0d46b5279700f9df786054aa5ee5 Rarible (erc721)
# 0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0 super rare (erc721)

# exchanges
# 0x1f9840a85d5af5bf1d1762f925bdaddc4201f984 uniswap (erc20)
# 0x6b3595068778dd592e39a122f4f5a5cf09c90fe2 sushiswap (erc20)

# social
# 0x58b6a8a3302369daec383334672404ee733ab239 livepeer (erc20)
# 0xb26631c6dda06ad89b93c71400d25692de89c068 minds (erc20)

#defi
# comp (erc20)
# yearn (erc20)

#Gambling
# 0x6337f5c6d181cf3ee9b31d381509898357238f13 Ethex (erc20)
# 0xf38edaf6fb7221ecf95995a9ecd4bb3c392a35fd dice2.win (erc20)

#collectibles


#stable coins :D
# 0xdac17f958d2ee523a2206206994597c13d831ec7 tether (erc20)

target = "0x6337f5c6d181cf3ee9b31d381509898357238f13"

start = time.time()

name = targetInfoDF[targetInfoDF["address"] == target].values[0][1].replace(" ", "")
print("Creating graph", name, "...", end='', flush=True)

tknTransactionsDF = targetDF[targetDF["tokenAddress"] == target][["from", "to", "timestamp"]]

nodes = pd.unique(tknTransactionsDF[["from", "to"]].values.ravel())
edges = tknTransactionsDF.values

graph = {}
graph["nodes"] = nodes.tolist()
graph["edges"] = edges.tolist()
graph["#nodes"] = len(nodes)
graph["#edges"] = len(edges)
graph["name"] = name
graph["edge"] = "from to timestamp"
graph["node"] = "addresses"
graph["comments"] = ""

m_file_name = name + ".json"
os.mkdir(graph_path + name)
with open(graph_path + name + "/" + m_file_name, 'w') as f:
    json.dump(graph, f, indent=4)
end = time.time()
print("took", end - start, "seconds.")

tknTransactionsDF

Creating graph Ethex ...took 26.390113830566406 seconds.

,from,to,timestamp
531257925,0xc88484537eacaa1287d0aa7ecff0a368ff0fa7c3,0xaa69856292199c0b5e591b396b362ed9b4581b4d,1517232810

## Contract Transactions Graph

In [26]:
name = "EthContractTransactions"
targetDF = internalTransactionsDF

contractTransactionsDF = targetDF[(targetDF["fromIsContract"] == 1) & 
                                  (targetDF["toIsContract"] == 1)
                                 ][["from", "to", "timestamp"]]

nodes = pd.unique(contractTransactionsDF[["from", "to"]].values.ravel())
edges = contractTransactionsDF.values

for e in edges:
        t = int(e[2])
        e[2] = t
        ts = int("1284101485")

    # if you encounter a "year is out of range" error the timestamp
    # may be in milliseconds, try `ts /= 1000` in that case
    #print(datetime.utcfromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'))
                
graph = {}
graph["nodes"] = nodes.tolist()
graph["edges"] = edges.tolist()
graph["#nodes"] = len(nodes)
graph["#edges"] = len(edges)
graph["name"] = "Eth Contract Transactions"
graph["edge"] = "from to timestamp"
graph["node"] = "addresses"
graph["comments"] = ""

print(len(nodes), len(edges))
#g_file_name = name + ".edgelist"
m_file_name = name + ".json"
os.mkdir(name)
with open(name + "/" + m_file_name, 'w') as f:
    json.dump(graph, f, indent=4)
#contractTransactionsDF.to_csv(os.getcwd() + "/" + name + "/" + g_file_name, sep ='\t', index=False, header=False)

print(contractTransactionsDF.shape[0])
contractTransactionsDF

3309220 52844135
52844135

,from,to,timestamp
0,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xedce883162179d4ed5eb9bb2e7dccf494d75b3a0,1499633567
1,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0x88de41a34871e239c52926f920efb4eefa0f3de3,1499633567
2,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xedce883162179d4ed5eb9bb2e7dccf494d75b3a0,1499633567
3,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xedce883162179d4ed5eb9bb2e7dccf494d75b3a0,1499633567
4,0xe5e0d92adf4ed8fd8a81947678ee47a35f32c50b,0xaaaf91d9b90df800df4f55c205fd6989c977e73a,1499633567
...,...,...,...
61158657,0x06012c8cf97bead5deae237070f9587f8e7a266d,0xecde0842e309c4b2d15c074512404207335f3096,1517319688
61158659,0x39243a59d34169eeb0cac2752a21b982408a0194,0x06012c8cf97bead5deae237070f9587f8e7a266d,1517319688
61158661,0x9b993ffb5df123822dc6cdecaedb6f2a61675a6e,0x5b28878c6a779b759a98544a36d25ea43724cd06,1517319688
61158662,0x9b993ffb5df123822dc6cdecaedb6f2a61675a6e,0xfae4ee59cdd86e3be9e8b90b53aa866327d7c090,1517319688
61158663,0x9b993ffb5df123822dc6cdecaedb6f2a61675a6e,0xfae4ee59cdd86e3be9e8b90b53aa866327d7c090,1517319688

## Print Edge List

In [15]:
name = "Ethex"
with open(graph_path + name + "/" + name + '.json') as f:
    graph_info = json.load(f)
graph_info['name'], graph_info['#nodes'], graph_info['#edges']

edges = graph_info["edges"]
out = graph_path + name + "/" + name + ".edgelist"

labels = {}
c = 0

start = time.time()
print("Creating graph", out, "...", end='', flush=True)
#get smallest time stamp
mint = sys.maxsize
for e in edges:
        t = int(e[2])
        if t < mint:
                mint = t
with open(out, "w") as o:
        for e in edges:
                u = e[0]
                v = e[1]
                t = e[2]
                if u not in labels:
                        labels[u] = c
                        c += 1
                u = labels[u]
                if v not in labels:
                        labels[v] = c
                        c += 1
                v = labels[v]
                o.write(str(u) + " " + str(v) + " " + str(int(t) - mint) + "\n")
end = time.time()
print("took", end - start, "seconds.")

Creating graph /DATA/7A/assets/Ethex/Ethex.edgelist ...took 0.0011932849884033203 seconds.